### ISSUE TITLE
Changing language has no effect

### ISSUE THREAD

**Issue by alani1** [stamp-web/stamp-web-aurelia#129]
On a clean copy I changed to chinese language, saved the settings. Nothing happend.

It seems the langauage preference is not stored. The payload sent to the server in PUT request ist  
{id: 1, category: "stamps", name: "pageSize", value: "250"}

I cant see the language here, where chinese should be something with id 2. also it does not send a PUT request if I just change the language. It seems the language dropdown is ignored.

on the JS console I have:
user-settings.js:116 Uncaught TypeError: Cannot read property 'toString' of undefined
(anonymous function) @ user-settings.js:116arrayEach @ vendor-bundle.js:4317forEach @ vendor-bundle.js:13084(anonymous function) @ user-settings.js:104arrayEach @ vendor-bundle.js:4317forEach @ vendor-bundle.js:13084save @ user-settings.js:103evaluate @ vendor-bundle.js:32335callSource @ vendor-bundle.js:35777(anonymous function) @ vendor-bundle.js:35801

**Comment by alani1** [comment]
the fix for sequence_gen also fixed my issues with preferences except this.

**Comment by jadrake75** [comment]
I am not sure I hooked up the language selection (since it has to happen very early in the process)  line 70 of main.js.  So that needs to be parameterized.  I can look tomorrow.  I may have had to revert some earlier code when aurelia went from alpha to beta before release that might have caused me to hard-code this.
