### ISSUE TITLE
Windows10

### ISSUE THREAD

**Issue by johntom** [stamp-web/stamp-web-aurelia#56]
Hi,
I just tired the repo with the following
Win 10
Node 0.12.7
npm 3.2.0
Followed all installation procedures for windows (too tall nate etc) but still get the following
Error
GET http://localhost:9000/jspm_packages/npm/core-js@0.9.18.js 404 (Not Found)f @ es6-module-loader.src.js:2612$__Object$defineProperty.value @ es6-module-loader.src.js:2787c @ es6-module-loader.src.js:377b @ es6-module-loader.src.js:365$__Object$defineProperty.value @ es6-module-loader.src.js:2786$__global.upgradeSystemLoader.e.fetch @ system.src.js:739$__global.upgradeSystemLoader.e.fetch @ system.src.js:1806$__global.upgradeSystemLoader.e.fetch @ system.src.js:1921(anonymous function) @ es6-module-loader.src.js:1525O @ es6-module-loader.src.js:1183K @ es6-module-loader.src.js:11427.y.when @ es6-module-loader.src.js:9307.v.run @ es6-module-loader.src.js:8213.a._drain @ es6-module-loader.src.js:973.a.drain @ es6-module-loader.src.js:62b @ es6-module-loader.src.js:268
es6-module-loader.src.js:140 Potentially unhandled rejection [3] Error loading "npm:core-js@0.9.18" at http://localhost:9000/jspm_packages/npm/core-js@0.9.18.js
Not Found: http://localhost:9000/jspm_packages/npm/core-js@0.9.18.js (WARNING: non-Error used)

**Comment by jadrake75** [comment]
I am using Windows 10 (installed clean last night) so that is not the problem

Did you setup the GitHub user id for git?  The instructions on the home page were actually originally from the Aurelia scaffold and honestly I have not updated to reflect up to date information because simply, while it is an open-source project there were no users/developers on it other than myself and a few acquaintances

You need to ensure you have run the following:

`jspm registry config GitHub`

jspm will attempt to compile vs. modules from GitHub.  If you have not provided your GitHub credentials (which I know you have - since you posted an issue) it will error out complaining you have exceeded the anonymous pulls

Not sure what the "too tall nate" comment is, but assuming you have node installed and jspm installed (I believe it needs to be globally installed) you would run

`npm install`
`jspm install`

then start the server with `gulp watch`

**Comment by johntom** [comment]
Hi,
Been building Aurelia apps for about 6 weeks and successfully migrated my apps from a win8 to win10 computer yesterday. Yes i've installed everything properly and did the jspm registry. Too Tall Nate refers to building some node components on windows computers and I just follow with the latest window versions. (see https://github.com/TooTallNate/node-gyp) I think that npm 3.2.0 is perhaps causing the issue as after the last reboot it was complaining about   C:\Aurelia\stamp-web-aurelia\dist\global-resources\index\default-value.js. Both  default-value.js and index.js files were sitting in global-sesource and a move to \Aurelia\stamp-web-aurelia\dist\global-resources\index directory now displayst he app but comes up with a bunch of other errors. Just curious what different path you took to install on win10?
John

**Comment by jadrake75** [comment]
The path I took was not fancy by any regards
- went to nodejs website and downloaded node js and installed
- installed git and GitHub app
- went to command line (git shell) and ran "npm install" in the folder.
  I "may" have installed jspm globally first via npm install.    The version
  of npm I am using is 2.11.3 which came with the release of NodeJS I
  installed (whatever was latest last night).  Ran into the jspm GitHub
  anonymous credentials issue, so updated the jspm registry and continued.

For the gyp stuff I guess I also installed Python 2.7.X.  It will not work
with Python 3.X (errors in some libraries)

I installed the OS around this time of night (2:05am local for me) - so my
brain was shutting down.... just resolved whatever error was reported along
the way.  Is there a reason you pulled the 3.X version of npm?  Why not
just use the version with Node?

**Comment by johntom** [comment]
I also installed python 2.x and started using npm 3.x because of the long path conflicts I've run into with some repos especially with sailsjs. When I have these issues I often get a "use a mac or linux box" response which I find unresonable since all the players claim total cross platform compatibility. I will explore further and get back to you. Since npm 3 is right around the corner, this might be am eventual issue for others.
Thanks

**Comment by johntom** [comment]
Deeper Dive:
My past expericence with various repos always leads to path of installing Community Edition of VS Studio (2015 on this computer) and using the following command >setx GYP_MSVS_VERSION 2015 /M
1) I reverted back to npm  2.13.4 and did a new git clone of repo
2) npm install I get a boatload of errors (see below)
3) I follow thread https://github.com/TooTallNate/node-gyp/issues/629 and https://github.com/TooTallNate/node-gyp/issues/339#issuecomment-111011412
4) Still don't have a working solution and wondering what different path taken to successful install
John

dump:

c:\Aurelia\stamp-web-aurelia (master)
λ npm install
\

> cson@1.6.2 preinstall c:\Aurelia\stamp-web-aurelia\node_modules\gulp-replace-task\node_modules\applause\node_modules\cson
> node ./cyclic.js

/

> ambi@2.2.0 preinstall c:\Aurelia\stamp-web-aurelia\node_modules\gulp-replace-task\node_modules\applause\node_modules\cson\node_modules\ambi
> node ./cyclic.js

## 

> typechecker@2.0.8 preinstall c:\Aurelia\stamp-web-aurelia\node_modules\gulp-replace-task\node_modules\applause\node_modules\cson\node_modules\ambi\node_modules\typechecker
> node ./cyclic.js
> 
> typechecker@2.0.8 preinstall c:\Aurelia\stamp-web-aurelia\node_modules\gulp-replace-task\node_modules\applause\node_modules\cson\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js

## 

> js2coffee@0.3.5 preinstall c:\Aurelia\stamp-web-aurelia\node_modules\gulp-replace-task\node_modules\applause\node_modules\cson\node_modules\js2coffee
> node ./cyclic.js

npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
\

> bufferutil@1.1.0 install c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

|
|

{lamb} if not defined npm_config_node_gyp (node "C:\Users\john\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets( 366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
 TargetFrameworkVersion or PlatformToolset may be set to an invalid version number . [c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\n ode_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcx proj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the fi le specified. [c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules \socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bu fferutil.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\john\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\Users\john\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
/

> utf-8-validate@1.1.0 install c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "C:\Users\john\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets( 366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
 TargetFrameworkVersion or PlatformToolset may be set to an invalid version number . [c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\n ode_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\validation .vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the fi le specified. [c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules \socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\buil d\validation.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\john\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\Users\john\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
/

> bufferutil@1.1.0 install c:\Aurelia\stamp-web-aurelia\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild
> ...

**Comment by jadrake75** [comment]
Well there is a definitely a difference.  You have MS Build Tools (aka Visual Studio 14?) installed. As I said I installed new last night (not an upgrade) and had nothing.  Even now I have the base, chrome, webstorm, MySQL and GitHub.  So it is complaining that it can not find CL.exe.  There are a few google results on this error.  They seem to indicate setting a path to your VS install or WindowsSDKDir  as an environment variable may be needed.

I am not sure how mine is "compiling" without it....

I was using the aurelia-i18next-parser tool at one time (or tried too - didn't work for me and wrote an issue to owner) and had a ton of gyp errors there.  However I did check and those dependencies are now gone from package.json - plus I would have seen it a day or two ago.

**Comment by johntom** [comment]
Hi,
Just purchased this New Win10 computer( an increadible deal from Lenovo) so a match to your new install. It would be nice if MS (https://blogs.windows.com/buildingapps/2015/05/12/bringing-node-js-to-windows-10-iot-core/) helped resolve these issues which don't seem to happen on macs or linux boxes as there are many threads on the problem. Feel free to close and If I resolve I will update post.
Thanks for your help,
John

**Comment by jadrake75** [comment]
Closing as per comment.  I will look into NPM 3.x and some point in the near future and resolve any build dependency issues.

**Comment by johntom** [comment]
Hi,
1) This computer did shp with win8.1 and my son immediately updated to win10 so my init reply was wrong.
2) It seems that the fix is pretty simple. Goto control panel ( a little tricky in win10),Programs and Features, Select MS Visual Sutdio Community 2015, modify, check select all options. (didn't want to take a chance with cherry picking)
3) Get a cup of coffee and wait... get another cup.
4) Npm install now runs without any errors and just a few warnings
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global marked@0.2.10 should be installed with -g
5) Gulp watch works!
6) Will test app later...
Hope this helps relieve the pain for someone else.
John

**Comment by jadrake75** [comment]
This is good to hear..... I could see the jshint needing to be global and should fix that in instructions.

Now.... to test the app, you will likely find it a very poor experience with just stamp-web-Aurelia because it is the client-only. :-)  There is an entirely different project that does the server.  Please remember this project has evolved one way or another since 1998.  In the summer of 2014 I rewrote the J2EE based server platform to be NodeJS based.  This makes it easier to deploy as you don't need Glassfish/J2EE transactional container.  Since I don't have equivalency between in this version of stamp-web with the other 10+ releases (I am working on it) I do not bundle the client and server together.  The latest server is actually supporting 3 versions of stamp-web client's (only the stamp-web-Aurelia and the abandoned stamp-web-material are on github).  The lack of equivalency is what has killed me with the last couple of versions and is a big focus for me to get to (even if it means some stuff is not as cleaned up as I'd like)

The way I run in development is by using nginx to be a reverse proxy between the client and server.  They are each executed as their own activities and patched through nginx to the appropriate backend.  The other requirement for the server is the need for a MySQL database.  I do have a database with 15000+ stamp records in it that is up on godaddy which I could provide credentials for if you wanted to look (performance won't be great since all REST calls will make a remote DB call.  Ideally the server + DB should be near-located.   Performance is not too bad from a remote client (it is the remote DB that is a killer).  I have not setup a demo/test server for this, although if there is great interest I suppose I could (I have the hardware at home for it).  It just has not been a priority for me, and I would also have to see some benefit in exposing it outward.   If you have a MySQL install/db I can also provide a .sql file which is a data dump of my production DB and you can import it easy enough (this is how I feeded the goDaddy DB).   In fact, the goDaddy DB is now nearly 3000 records short of the production DB (so I have been busy buying and entering stamps)

Here is the server/service UX.  The setup instructions here are actually pretty decent.
https://github.com/stamp-web/stamp-webservices

**Comment by johntom** [comment]
Thanks, I already downloaded your backend but had to hold back as I have to get some things done, also haven't installed Mysql on this computer yet. I use Sailsjs for my backend stuff and while I use mongodb for all new stuff I have one major client where I wrote the entire API getting Mysql data from a remote side and have excellent performance. Sailsjs is really great and if interested I'm happy to share code with you.

John
