### ISSUE TITLE
Problem with dialogs

### ISSUE THREAD

**Issue by jeremy-holt** [stamp-web/stamp-web-aurelia#94]
I just cloned this since it looks like a fabulous learning resource. However, under settings/management  are the drop downs supposed to self populate with countries, catalogs etc?

I can't quite work out how to get it running - is it supposed to display existing stamp collections?

**Comment by jadrake75** [comment]
Thanks for your comments.  You need a stamp-webservices (https://github.com/stamp-web/stamp-webservices) or equivalent server platform to effectively "use" the software.  This is available from the stamp-web in GitHub, but involves more setup (like MySQL etc.)  I had a defect #1 , however we closed it since in reality it was not of a lot of value (and I didn't want to have to maintain the solution.

I have considered setting up a sample "webservices" out there which you could reverse proxy in (this is what I do when I run/test) however again, there is not really a lot of value to me to do so (and where would I get the time)

Based on this, I will add some notes to the README on how to setup the system (ie. point to the webservices project etc)

**Comment by jeremy-holt** [comment]
OK - thanks for the feedback
